### ISSUE TITLE
Allow external-name annotation to be constructed from spec and spec fields to be initialized from external-name

### ISSUE THREAD

**Issue by ulucinar** [crossplane-contrib/terrajet#119]
### What problem are you facing?

Like manually coded in native providers, in certain cases, we need a mechanism in terrajet to allow the external-name to be 
constructed from information available from spec & provider configuration. This should also work in the opposite direction, i.e., when an external name is specified by the user, we should be able to late-initialize certain spec fields from the information made available in the external-name. 

### How could Terrajet help solve your problem?

An example from tf-provider-azure is the `v1alpha1.ResourceGroup`:

```
apiVersion: resource.azure.tf.crossplane.io/v1alpha1
kind: ResourceGroup
metadata:
  name: example
  annotations:
    crossplane.io/external-name: /subscriptions/<subscription id>/resourceGroups/example
spec:
  forProvider:
    name: example-resourcegroup
    location: "East US"
    tags:
      provisioner: crossplane
  providerConfigRef:
    name: example
```
In this example, ideally, the users should be able to:
- Specify the required parameters for a resource group, i.e. name & location in the spec to provision a new resource group, and the provider correctly populates the external-name annotation (which is the current case btw)
- Specify only the external-name annotation in the manifest, and the provider should be able to populate the resource group name via a coded extension point (probably part of the `Terraformed` interface).
