### ISSUE TITLE
Cannot use Paved path as a key in Kubernetes secret

### ISSUE THREAD

**Issue by ulucinar** [crossplane-contrib/terrajet#93]
### What happened?

While trying to store sensitive data from a `v1alpha1.KubernetesCluster` in provider-tf-azure, after setting the `writeConnectionSecretToRef` field, I observed the following logs:

```
2021-10-07T23:33:55.924+0300    DEBUG   controller-runtime.manager.events       Warning {"object": {"kind":"KubernetesCluster","name":"example","uid":"1a8fbb21-9823-4869-8c3a-37b76bd9e1bc","apiVersion":"kubernetes.azure.tf.crossplane.io/v1alpha1","resourceVersion":"643827"}, "reason": "CannotPublishConnectionDetails", "message": "cannot create or update connection secret: cannot create object: Secret \"test-k8s\" is invalid: [data[kube_config[0].password]: Invalid value: \"kube_config[0].password\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[kube_config[0].client_certificate]: Invalid value: \"kube_config[0].client_certificate\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[kube_config[0].client_key]: Invalid value: \"kube_config[0].client_key\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[kube_config[0].cluster_ca_certificate]: Invalid value: \"kube_config[0].cluster_ca_certificate\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+')]"}
```

### How can we reproduce it?

Using provider-tf-azure (from a local build):
```
apiVersion: kubernetes.azure.tf.crossplane.io/v1alpha1
kind: KubernetesCluster
metadata:
  name: example
spec:
  writeConnectionSecretToRef:
    name: example-kubeconfig
    namespace: crossplane-system
  forProvider:
    name: "kubernetesCluster1"
    location: "East US"
    resourceGroupName: "example-rg"
    dnsPrefix: "exampleaks1"
    defaultNodePool:
      - name: default
        nodeCount: 1
        vmSize: "Standard_D2_v2"
    identity:
      - type: "SystemAssigned"
    tags:
      purpose: example
  providerConfigRef:
    name: example

```
